-----------------------------------
-- Zone: Outer_RaKaznar_[U1]
-- Achuka
-----------------------------------
local ID = require("scripts/zones/Outer_RaKaznar_[U1]/IDs")
require("scripts/globals/pathfind")
-----------------------------------
local entity = {}
	
entity.onMobSpawn = function(mob)
	mob:renameEntity("Plouton")
	mob:setMobMod(xi.mobMod.DRAW_IN, 10)
	mob:setMod(xi.mod.DMG, -8000)
	mob:setMod(xi.mod.ACC, 2300)
	mob:setMod(xi.mod.ATT, 2200)
	mob:setMod(xi.mod.MATT, 1500)
	mob:setMod(xi.mod.MACC, 2200)
	mob:setMod(xi.mod.FIRE_SDT, 500)
    mob:setMod(xi.mod.ICE_SDT, 500)
    mob:setMod(xi.mod.WIND_SDT, 500)
	mob:setMod(xi.mod.EARTH_SDT, 500)
    mob:setMod(xi.mod.THUNDER_SDT, 500)
    mob:setMod(xi.mod.WATER_SDT, 500)
    mob:setMod(xi.mod.LIGHT_SDT, 500)
    mob:setMod(xi.mod.DARK_SDT, 500)
	mob:setMod(xi.mod.REGAIN, 10)
	mob:setMod(xi.mod.TRIPLE_ATTACK, 50)
	SetServerVariable("IncessantVoidUse", 0)
	local pos = player:getPos()
	mob:setPos(pos.x, pos.y, pos.z, pos.r)
end

entity.onMobEngaged = function(mob, player)
	player:PrintToPlayer("Plouton: Not even Twilight can devour me! What chance do you think you have!", 13)
end

entity.onMobFight = function(mob, target)
	local HPP = mob:getHPP()
	if HPP <= 90 and GetServerVariable("IncessantVoidUse") == 0 then
        mob:useMobAbility(437) -- should all be 3144
		mob:setAnimationSub(1)
		SetServerVariable("IncessantVoidUse", 1)
		mob:setMod(xi.mod.FIRE_SDT, 1300)
		mob:setMod(xi.mod.ICE_SDT, 500)
		mob:setMod(xi.mod.WIND_SDT, 500)
		mob:setMod(xi.mod.EARTH_SDT, 500)
		mob:setMod(xi.mod.THUNDER_SDT, 500)
		mob:setMod(xi.mod.WATER_SDT, 500)
		mob:setMod(xi.mod.LIGHT_SDT, 500)
		mob:setMod(xi.mod.DARK_SDT, 500)
		mob:setMod(xi.mod.FIRE_ABSORB, 0)
		mob:setMod(xi.mod.ICE_ABSORB, 0)
		mob:setMod(xi.mod.WIND_ABSORB, 0)
		mob:setMod(xi.mod.EARTH_ABSORB, 0)
		mob:setMod(xi.mod.LTNG_ABSORB, 0)
		mob:setMod(xi.mod.WATER_ABSORB, 100)
		mob:setMod(xi.mod.LIGHT_ABSORB, 0)
		mob:setMod(xi.mod.DARK_ABSORB, 0)
		mob:setMod(xi.mod.SLASH_SDT, 1000)
		mob:setMod(xi.mod.PIERCE_SDT, 1000)
		mob:setMod(xi.mod.IMPACT_SDT, 1000)
		mob:setMod(xi.mod.HTH_SDT, 1000)
		player:PrintToPlayer("Plouton: Have we gotten serious yet?", 13)
	elseif HPP <= 80 and GetServerVariable("IncessantVoidUse") == 1 then
        mob:useMobAbility(562) -- might be 3144
		SetServerVariable("IncessantVoidUse", 2)
		mob:setMod(xi.mod.FIRE_SDT, 500)
		mob:setMod(xi.mod.ICE_SDT, 1300)
		mob:setMod(xi.mod.WIND_SDT, 500)
		mob:setMod(xi.mod.EARTH_SDT, 500)
		mob:setMod(xi.mod.THUNDER_SDT, 500)
		mob:setMod(xi.mod.WATER_SDT, 500)
		mob:setMod(xi.mod.LIGHT_SDT, 500)
		mob:setMod(xi.mod.DARK_SDT, 500)
		mob:setMod(xi.mod.FIRE_ABSORB, 100)
		mob:setMod(xi.mod.ICE_ABSORB, 0)
		mob:setMod(xi.mod.WIND_ABSORB, 0)
		mob:setMod(xi.mod.EARTH_ABSORB, 0)
		mob:setMod(xi.mod.LTNG_ABSORB, 0)
		mob:setMod(xi.mod.WATER_ABSORB, 0)
		mob:setMod(xi.mod.LIGHT_ABSORB, 0)
		mob:setMod(xi.mod.DARK_ABSORB, 0)
		mob:setMod(xi.mod.SLASH_SDT, 1000)
		mob:setMod(xi.mod.PIERCE_SDT, 1000)
		mob:setMod(xi.mod.IMPACT_SDT, 1000)
		mob:setMod(xi.mod.HTH_SDT, 1000)
	elseif HPP <= 70 and GetServerVariable("IncessantVoidUse") == 2 then
        mob:useMobAbility(631) -- might be 3144
		SetServerVariable("IncessantVoidUse", 3)
		mob:setMod(xi.mod.FIRE_SDT, 500)
		mob:setMod(xi.mod.ICE_SDT, 500)
		mob:setMod(xi.mod.WIND_SDT, 1300)
		mob:setMod(xi.mod.EARTH_SDT, 500)
		mob:setMod(xi.mod.THUNDER_SDT, 500)
		mob:setMod(xi.mod.WATER_SDT, 500)
		mob:setMod(xi.mod.LIGHT_SDT, 500)
		mob:setMod(xi.mod.DARK_SDT, 500)
		mob:setMod(xi.mod.FIRE_ABSORB, 0)
		mob:setMod(xi.mod.ICE_ABSORB, 100)
		mob:setMod(xi.mod.WIND_ABSORB, 0)
		mob:setMod(xi.mod.EARTH_ABSORB, 0)
		mob:setMod(xi.mod.LTNG_ABSORB, 0)
		mob:setMod(xi.mod.WATER_ABSORB, 0)
		mob:setMod(xi.mod.LIGHT_ABSORB, 0)
		mob:setMod(xi.mod.DARK_ABSORB, 0)
		mob:setMod(xi.mod.SLASH_SDT, 1000)
		mob:setMod(xi.mod.PIERCE_SDT, 1000)
		mob:setMod(xi.mod.IMPACT_SDT, 1000)
		mob:setMod(xi.mod.HTH_SDT, 1000)
		player:PrintToPlayer("Plouton: It seems I may have slightly underestimated you, as you have I.", 13)
	elseif HPP <= 60 and GetServerVariable("IncessantVoidUse") == 3 then
        mob:useMobAbility(671) -- might be 3144
		SetServerVariable("IncessantVoidUse", 4)
		mob:setMod(xi.mod.FIRE_SDT, 500)
		mob:setMod(xi.mod.ICE_SDT, 500)
		mob:setMod(xi.mod.WIND_SDT, 500)
		mob:setMod(xi.mod.EARTH_SDT, 1300)
		mob:setMod(xi.mod.THUNDER_SDT, 500)
		mob:setMod(xi.mod.WATER_SDT, 500)
		mob:setMod(xi.mod.LIGHT_SDT, 500)
		mob:setMod(xi.mod.DARK_SDT, 500)
		mob:setMod(xi.mod.FIRE_ABSORB, 0)
		mob:setMod(xi.mod.ICE_ABSORB, 0)
		mob:setMod(xi.mod.WIND_ABSORB, 100)
		mob:setMod(xi.mod.EARTH_ABSORB, 0)
		mob:setMod(xi.mod.LTNG_ABSORB, 0)
		mob:setMod(xi.mod.WATER_ABSORB, 0)
		mob:setMod(xi.mod.LIGHT_ABSORB, 0)
		mob:setMod(xi.mod.DARK_ABSORB, 0)
		mob:setMod(xi.mod.SLASH_SDT, 1000)
		mob:setMod(xi.mod.PIERCE_SDT, 1000)
		mob:setMod(xi.mod.IMPACT_SDT, 1000)
		mob:setMod(xi.mod.HTH_SDT, 1000)
	elseif HPP <= 50 and GetServerVariable("IncessantVoidUse") == 4 then
        mob:useMobAbility(690) -- might be 3144
		SetServerVariable("IncessantVoidUse", 5)
		mob:setMod(xi.mod.FIRE_SDT, 500)
		mob:setMod(xi.mod.ICE_SDT, 500)
		mob:setMod(xi.mod.WIND_SDT, 500)
		mob:setMod(xi.mod.EARTH_SDT, 500)
		mob:setMod(xi.mod.THUNDER_SDT, 1300)
		mob:setMod(xi.mod.WATER_SDT, 500)
		mob:setMod(xi.mod.LIGHT_SDT, 500)
		mob:setMod(xi.mod.DARK_SDT, 500)
		mob:setMod(xi.mod.FIRE_ABSORB, 0)
		mob:setMod(xi.mod.ICE_ABSORB, 0)
		mob:setMod(xi.mod.WIND_ABSORB, 0)
		mob:setMod(xi.mod.EARTH_ABSORB, 100)
		mob:setMod(xi.mod.LTNG_ABSORB, 0)
		mob:setMod(xi.mod.WATER_ABSORB, 0)
		mob:setMod(xi.mod.LIGHT_ABSORB, 0)
		mob:setMod(xi.mod.DARK_ABSORB, 0)
		mob:setMod(xi.mod.SLASH_SDT, 1000)
		mob:setMod(xi.mod.PIERCE_SDT, 1000)
		mob:setMod(xi.mod.IMPACT_SDT, 1000)
		mob:setMod(xi.mod.HTH_SDT, 1000)
	elseif HPP <= 40 and GetServerVariable("IncessantVoidUse") == 5 then
        mob:useMobAbility(695) -- might be 3144
		SetServerVariable("IncessantVoidUse", 6)
		mob:setMod(xi.mod.FIRE_SDT, 500)
		mob:setMod(xi.mod.ICE_SDT, 500)
		mob:setMod(xi.mod.WIND_SDT, 500)
		mob:setMod(xi.mod.EARTH_SDT, 500)
		mob:setMod(xi.mod.THUNDER_SDT, 500)
		mob:setMod(xi.mod.WATER_SDT, 500)
		mob:setMod(xi.mod.LIGHT_SDT, 1300)
		mob:setMod(xi.mod.DARK_SDT, 500)
		mob:setMod(xi.mod.FIRE_ABSORB, 0)
		mob:setMod(xi.mod.ICE_ABSORB, 0)
		mob:setMod(xi.mod.WIND_ABSORB, 0)
		mob:setMod(xi.mod.EARTH_ABSORB, 0)
		mob:setMod(xi.mod.LTNG_ABSORB, 0)
		mob:setMod(xi.mod.WATER_ABSORB, 0)
		mob:setMod(xi.mod.LIGHT_ABSORB, 0)
		mob:setMod(xi.mod.DARK_ABSORB, 100)
		mob:setMod(xi.mod.SLASH_SDT, 1000)
		mob:setMod(xi.mod.PIERCE_SDT, 1000)
		mob:setMod(xi.mod.IMPACT_SDT, 1000)
		mob:setMod(xi.mod.HTH_SDT, 1000)
	elseif HPP <= 30 and GetServerVariable("IncessantVoidUse") == 6 then
        mob:useMobAbility(813) -- might be 3144
		SetServerVariable("IncessantVoidUse", 7)
		mob:setAnimationSub(2)
		mob:setMod(xi.mod.FIRE_SDT, 500)
		mob:setMod(xi.mod.ICE_SDT, 500)
		mob:setMod(xi.mod.WIND_SDT, 500)
		mob:setMod(xi.mod.EARTH_SDT, 500)
		mob:setMod(xi.mod.THUNDER_SDT, 500)
		mob:setMod(xi.mod.WATER_SDT, 500)
		mob:setMod(xi.mod.LIGHT_SDT, 500)
		mob:setMod(xi.mod.DARK_SDT, 1300)
		mob:setMod(xi.mod.FIRE_ABSORB, 0)
		mob:setMod(xi.mod.ICE_ABSORB, 0)
		mob:setMod(xi.mod.WIND_ABSORB, 0)
		mob:setMod(xi.mod.EARTH_ABSORB, 0)
		mob:setMod(xi.mod.LTNG_ABSORB, 0)
		mob:setMod(xi.mod.WATER_ABSORB, 0)
		mob:setMod(xi.mod.LIGHT_ABSORB, 100)
		mob:setMod(xi.mod.DARK_ABSORB, 0)
		mob:setMod(xi.mod.SLASH_SDT, 2000)
		mob:setMod(xi.mod.PIERCE_SDT, 10)
		mob:setMod(xi.mod.IMPACT_SDT, 10)
		mob:setMod(xi.mod.HTH_SDT, 10)
		player:PrintToPlayer("Plouton: You shall regret crossing me.", 13)
	elseif HPP <= 20 and GetServerVariable("IncessantVoidUse") == 7 then
        mob:useMobAbility(951) -- might be 3144
		SetServerVariable("IncessantVoidUse", 8)
		mob:setMod(xi.mod.FIRE_SDT, 500)
		mob:setMod(xi.mod.ICE_SDT, 500)
		mob:setMod(xi.mod.WIND_SDT, 500)
		mob:setMod(xi.mod.EARTH_SDT, 500)
		mob:setMod(xi.mod.THUNDER_SDT, 500)
		mob:setMod(xi.mod.WATER_SDT, 500)
		mob:setMod(xi.mod.LIGHT_SDT, 500)
		mob:setMod(xi.mod.DARK_SDT, 500)
		mob:setMod(xi.mod.FIRE_ABSORB, 0)
		mob:setMod(xi.mod.ICE_ABSORB, 0)
		mob:setMod(xi.mod.WIND_ABSORB, 0)
		mob:setMod(xi.mod.EARTH_ABSORB, 0)
		mob:setMod(xi.mod.LTNG_ABSORB, 0)
		mob:setMod(xi.mod.WATER_ABSORB, 0)
		mob:setMod(xi.mod.LIGHT_ABSORB, 0)
		mob:setMod(xi.mod.DARK_ABSORB, 0)
		mob:setMod(xi.mod.SLASH_SDT, 10)
		mob:setMod(xi.mod.PIERCE_SDT, 2000)
		mob:setMod(xi.mod.IMPACT_SDT, 10)
		mob:setMod(xi.mod.HTH_SDT, 10)
	elseif HPP <= 10 and GetServerVariable("IncessantVoidUse") == 8 then
        mob:useMobAbility(958) -- might be 3144
		SetServerVariable("IncessantVoidUse", 9)
		mob:setMod(xi.mod.FIRE_SDT, 500)
		mob:setMod(xi.mod.ICE_SDT, 500)
		mob:setMod(xi.mod.WIND_SDT, 500)
		mob:setMod(xi.mod.EARTH_SDT, 500)
		mob:setMod(xi.mod.THUNDER_SDT, 500)
		mob:setMod(xi.mod.WATER_SDT, 500)
		mob:setMod(xi.mod.LIGHT_SDT, 500)
		mob:setMod(xi.mod.DARK_SDT, 500)
		mob:setMod(xi.mod.FIRE_ABSORB, 0)
		mob:setMod(xi.mod.ICE_ABSORB, 0)
		mob:setMod(xi.mod.WIND_ABSORB, 0)
		mob:setMod(xi.mod.EARTH_ABSORB, 0)
		mob:setMod(xi.mod.LTNG_ABSORB, 0)
		mob:setMod(xi.mod.WATER_ABSORB, 0)
		mob:setMod(xi.mod.LIGHT_ABSORB, 0)
		mob:setMod(xi.mod.DARK_ABSORB, 0)
		mob:setMod(xi.mod.SLASH_SDT, 10)
		mob:setMod(xi.mod.PIERCE_SDT, 10)
		mob:setMod(xi.mod.IMPACT_SDT, 2000)
		mob:setMod(xi.mod.HTH_SDT, 2000)
	end
end		


entity.onMobDeath = function(mob, player, isKiller, noKiller)
	if (GetServerVariable("P1Boss3") == 1) or
		(GetServerVariable("P2Boss3") == 1) or
		(GetServerVariable("P3Boss2") == 1)
	then
		player:changeMusic(0, 74)
		player:changeMusic(1, 74)
		player:changeMusic(2, 74)
		player:changeMusic(3, 74)
		player:changeMusic(4, 74)
	else
		player:changeMusic(0, 62)
		player:changeMusic(1, 62)
		player:changeMusic(2, 62)
		player:changeMusic(3, 62)
		player:changeMusic(4, 62)
	end
	player:PrintToPlayer("Plouton: I shall control the Styx! Not that worthless hooded one...", 13)
end

entity.onMobRoam = function(mob, player)
	if GetServerVariable("Vag1Active") == 0 then
		DespawnMob(17903709)
	end
	if GetServerVariable("Vag2Active") == 0 then
		DespawnMob(17903768)
	end
	if GetServerVariable("Vag3Active") == 0 then
		DespawnMob(17903825)
	end
end

entity.onMobDespawn = function(mob)

end

return entity