-----------------------------------
-- func: nmhuntone list 150 tier 1-3
-- desc: prints out list of kill counts
-----------------------------------
local commandObj = {}

commandObj.cmdprops =
{
    permission = 0,
    parameters = 'is'
}

local function error(player, msg)
    player:printToPlayer(msg)
    player:printToPlayer('!nmhuntone <tier>')
end

commandObj.onTrigger = function(player, amount)

    if amount == nil or amount < 1 then
        error(player, 'Invalid tier, please enter 1 - 3.')
        return
    end

local aa = player:getCharVar('[NMHunt]DE_Ailmar')
local ab = player:getCharVar('[NMHunt]DE_Amara')
local ac = player:getCharVar('[NMHunt]DE_Aquarun')
local ad = player:getCharVar('[NMHunt]DE_Axil')
local ae = player:getCharVar('[NMHunt]DE_Bellas')
local af = player:getCharVar('[NMHunt]DE_Bonna')
local ag = player:getCharVar('[NMHunt]DE_Brina')
local ah = player:getCharVar('[NMHunt]DE_Celestia')
local ai = player:getCharVar('[NMHunt]DE_Cluym')
local aj = player:getCharVar('[NMHunt]DE_Daemeon')
local ak = player:getCharVar('[NMHunt]DE_Dark Rain')
local al = player:getCharVar('[NMHunt]DE_Diamond')
local am = player:getCharVar('[NMHunt]DE_Dracyian')
local an = player:getCharVar('[NMHunt]DE_Edmyla')
local ao = player:getCharVar('[NMHunt]DE_Elora')
local ap = player:getCharVar('[NMHunt]DE_Estelar')
local aq = player:getCharVar('[NMHunt]DE_Finrod')
local ar = player:getCharVar('[NMHunt]DE_Fundar')
local as = player:getCharVar('[NMHunt]DE_Gelda')
local at = player:getCharVar('[NMHunt]DE_Golvig')
local au = player:getCharVar('[NMHunt]DE_Haemir')
local av = player:getCharVar('[NMHunt]DE_Igor')
local aw = player:getCharVar('[NMHunt]DE_Ithi')
local ax = player:getCharVar('[NMHunt]DE_Jhaan')
local ay = player:getCharVar('[NMHunt]DE_Keara')
local az = player:getCharVar('[NMHunt]DE_Kyla')
local ba = player:getCharVar('[NMHunt]DE_Lavatius')
local bb = player:getCharVar('[NMHunt]DE_Lunarex')
local bc = player:getCharVar('[NMHunt]DE_Malumka')
local bd = player:getCharVar('[NMHunt]DE_Misi')
local be = player:getCharVar('[NMHunt]DE_Mysris')
local bf = player:getCharVar('[NMHunt]DE_Nemredilth')
local bg = player:getCharVar('[NMHunt]DE_Nindr')
local bh = player:getCharVar('[NMHunt]DE_Olwyn')
local bi = player:getCharVar('[NMHunt]DE_Orym')
local bj = player:getCharVar('[NMHunt]DE_Pondra')
local bk = player:getCharVar('[NMHunt]DE_Ragna')
local bl = player:getCharVar('[NMHunt]DE_Rennyn')
local bm = player:getCharVar('[NMHunt]DE_Sabir')
local bn = player:getCharVar('[NMHunt]DE_Sapphire')
local bo = player:getCharVar('[NMHunt]DE_Shikta')
local bp = player:getCharVar('[NMHunt]DE_Slyvek')
local bq = player:getCharVar('[NMHunt]DE_Star Light')
local br = player:getCharVar('[NMHunt]DE_Sunshine')
local bs = player:getCharVar('[NMHunt]DE_Tanulia')
local bt = player:getCharVar('[NMHunt]DE_Tisnip')
local bu = player:getCharVar('[NMHunt]DE_Turvass')
local bv = player:getCharVar('[NMHunt]DE_Vaegon')
local bw = player:getCharVar('[NMHunt]DE_Vinelle')
local bx = player:getCharVar('[NMHunt]DE_Wilkass')

local by = player:getCharVar('[NMHunt]DE_Akibrus')
local bz = player:getCharVar('[NMHunt]DE_Amerstal')
local ca = player:getCharVar('[NMHunt]DE_Asralyn')
local cb = player:getCharVar('[NMHunt]DE_Ayldrad')
local cc = player:getCharVar('[NMHunt]DE_Bellesta')
local cd = player:getCharVar('[NMHunt]DE_Bonnwynn')
local ce = player:getCharVar('[NMHunt]DE_Brobek')
local cf = player:getCharVar('[NMHunt]DE_Chalia')
local cg = player:getCharVar('[NMHunt]DE_Coalak')
local ch = player:getCharVar('[NMHunt]DE_Daernip')
local ci = player:getCharVar('[NMHunt]DE_Darvyn')
local cj = player:getCharVar('[NMHunt]DE_Digroi')
local ck = player:getCharVar('[NMHunt]DE_Dray')
local cl = player:getCharVar('[NMHunt]DE_Eiki')
local cm = player:getCharVar('[NMHunt]DE_Elwin')
local cn = player:getCharVar('[NMHunt]DE_Fabien')
local co = player:getCharVar('[NMHunt]DE_Flammedra')
local cp = player:getCharVar('[NMHunt]DE_Gaemon')
local cq = player:getCharVar('[NMHunt]DE_Gembelle')
local cr = player:getCharVar('[NMHunt]DE_Gremin')
local cs = player:getCharVar('[NMHunt]DE_Hastos')
local ct = player:getCharVar('[NMHunt]DE_Ilbryn')
local cu = player:getCharVar('[NMHunt]DE_Jaderyn')
local cv = player:getCharVar('[NMHunt]DE_Jinvia')
local cw = player:getCharVar('[NMHunt]DE_Kezda')
local cx = player:getCharVar('[NMHunt]DE_Kymil')
local cy = player:getCharVar('[NMHunt]DE_Lavinia')
local cz = player:getCharVar('[NMHunt]DE_Lymseia')
local da = player:getCharVar('[NMHunt]DE_Merlara')
local db = player:getCharVar('[NMHunt]DE_Misma')
local dc = player:getCharVar('[NMHunt]DE_Mystique')
local dd = player:getCharVar('[NMHunt]DE_Nesterin')
local de = player:getCharVar('[NMHunt]DE_Noi')
local df = player:getCharVar('[NMHunt]DE_Onas')
local dg = player:getCharVar('[NMHunt]DE_Pearl Moon')
local dh = player:getCharVar('[NMHunt]DE_Pondral')
local di = player:getCharVar('[NMHunt]DE_Ragriel')
local dj = player:getCharVar('[NMHunt]DE_Reyda')
local dk = player:getCharVar('[NMHunt]DE_Saeya')
local dl = player:getCharVar('[NMHunt]DE_Sarielle')
local dm = player:getCharVar('[NMHunt]DE_Shirmyl')
local dn = player:getCharVar('[NMHunt]DE_Snowflake')
local doo = player:getCharVar('[NMHunt]DE_Starburst')
local dp = player:getCharVar('[NMHunt]DE_Sybella')
local dq = player:getCharVar('[NMHunt]DE_Tazlen')
local dr = player:getCharVar('[NMHunt]DE_Tisthel')
local ds = player:getCharVar('[NMHunt]DE_Twilight')
local dt = player:getCharVar('[NMHunt]DE_Vaella')
local du = player:getCharVar('[NMHunt]DE_Virfi')
local dv = player:getCharVar('[NMHunt]DE_Wiska')

local dw = player:getCharVar('[NMHunt]DE_Akkar')
local dx = player:getCharVar('[NMHunt]DE_Angor')
local dy = player:getCharVar('[NMHunt]DE_Astra')
local dz = player:getCharVar('[NMHunt]DE_Azariah')
local ea = player:getCharVar('[NMHunt]DE_Belstram')
local eb = player:getCharVar('[NMHunt]DE_Bragi')
local ec = player:getCharVar('[NMHunt]DE_Brulin')
local ed = player:getCharVar('[NMHunt]DE_Chandrelle')
local ee = player:getCharVar('[NMHunt]DE_Corym')
local ef = player:getCharVar('[NMHunt]DE_Dagen')
local eg = player:getCharVar('[NMHunt]DE_Delvin')
local eh = player:getCharVar('[NMHunt]DE_Dimlinn')
local ei = player:getCharVar('[NMHunt]DE_Drusila')
local ej = player:getCharVar('[NMHunt]DE_Eilivur')
local ek = player:getCharVar('[NMHunt]DE_Engar')
local el = player:getCharVar('[NMHunt]DE_Fada')
local em = player:getCharVar('[NMHunt]DE_Floki')
local en = player:getCharVar('[NMHunt]DE_Galdor')
local eo = player:getCharVar('[NMHunt]DE_Glacitus')
local ep = player:getCharVar('[NMHunt]DE_Gusak')
local eq = player:getCharVar('[NMHunt]DE_Heptin')
local er = player:getCharVar('[NMHunt]DE_Ilyrana')
local es = player:getCharVar('[NMHunt]DE_Jai-Blynn')
local et = player:getCharVar('[NMHunt]DE_Jodis')
local eu = player:getCharVar('[NMHunt]DE_Killin')
local ev = player:getCharVar('[NMHunt]DE_Kyra')
local ew = player:getCharVar('[NMHunt]DE_Lija')
local ex = player:getCharVar('[NMHunt]DE_Lyra')
local ey = player:getCharVar('[NMHunt]DE_Midnight')
local ez = player:getCharVar('[NMHunt]DE_Mistmael')
local fa = player:getCharVar('[NMHunt]DE_Nalra')
local fb = player:getCharVar('[NMHunt]DE_Night Moon')
local fc = player:getCharVar('[NMHunt]DE_Norok')
local fd = player:getCharVar('[NMHunt]DE_Onnyx')
local fe = player:getCharVar('[NMHunt]DE_Peregrine')
local ff = player:getCharVar('[NMHunt]DE_Prodos')
local fg = player:getCharVar('[NMHunt]DE_Rainbow')
local fh = player:getCharVar('[NMHunt]DE_Rhenalyrr')
local fi = player:getCharVar('[NMHunt]DE_Sakakara')
local fj = player:getCharVar('[NMHunt]DE_Serpretus')
local fk = player:getCharVar('[NMHunt]DE_Silver Star')
local fl = player:getCharVar('[NMHunt]DE_Sola')
local fm = player:getCharVar('[NMHunt]DE_Stardust')
local fn = player:getCharVar('[NMHunt]DE_Syfas')
local fo = player:getCharVar('[NMHunt]DE_Tendris')
local fp = player:getCharVar('[NMHunt]DE_Tiznys')
local fq = player:getCharVar('[NMHunt]DE_Twinkle')
local fr = player:getCharVar('[NMHunt]DE_Vasha')
local fs = player:getCharVar('[NMHunt]DE_Vixen')
local ft = player:getCharVar('[NMHunt]DE_Wispmaral')

if amount == 1 then 

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('NM Hunt Kill Count Tier 1--Current Kills are %s of 50--------------------------------------',player:getCharVar('[NMHunt]TOneKills')), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'),  xi.msg.channel.SYSTEM_3)
player:printToPlayer(string.format('Ailmar %s | Amara %s | Aquarun %s | Axil %s | Bellas %s | ',aa,ab,ac,ad,ae), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Bonna %s | Brina %s | Celestia %s | Cluym %s | Daemeon %s | ',af,ag,ah,ai,aj), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Dark Rain %s | Diamond %s | Dracyian %s | Edmyla %s | Elora %s | ',ak,al,am,an,ao), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Estelar %s | Finrod %s | Fundar %s | Gelda %s | Golvig %s | ',ap,aq,ar,as,at), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Haemir %s | Igor %s | Ithi %s | Jhaan %s | Keara %s | ',au,av,aw,ax,ay), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Kyla %s | Lavatius %s | Lunarex %s | Malumka %s | Misi %s | ',az,ba,bb,bc,bd), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Mysris %s | Nemredilth %s | Nindr  %s | Olwyn %s | Orym  %s | ',be,bf,bg,bh,bi), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Pondra %s | Ragna %s | Rennyn %s | Sabir  %s | Sapphire %s | ',bj,bk,bl,bm,bn), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Shikta %s | Slyvek %s | Star Light %s | Sunshine %s | Tanulia %s | ',bo,bp,bq,br,bs), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Tisnip %s | Turvass %s | Vaegon  %s | Vinelle %s | Wilkass %s | ',bt,bu,bv,bw,bx), 3, xi.msg.channel.system_3)

elseif amount == 2 then 

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('NM Hunt Kill Count Tier 2--Current Kills are %s of 50--------------------------------------',player:getCharVar('[NMHunt]TTwoKills')), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'),  xi.msg.channel.SYSTEM_3)
player:printToPlayer(string.format('Akibrus %s | Amerstal %s | Asralyn %s | Ayldrad %s | Bellesta %s | ',by,bz,ca,cb,cc), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Bonnwynn %s | Brobek %s | Chalia %s | Coalak %s | Daernip %s | ',cd,ce,cf,cg,ch), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Darvyn %s | Digroi %s | Dray %s | Eiki %s | Elwin %s | ',ci,cj,ck,cl,cm), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Fabien %s | Flammedra %s | Gaemon %s | Gembelle %s | Gremin %s | ',cn,co,cp,cq,cr), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Hastos %s | Ilbryn %s | Jaderyn %s | Jinvia %s | Kezda %s | ',cs,ct,cu,cv,cw), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Kymil %s | Lavinia %s | Lymseia  %s | Merlara %s | Misma %s | ',cx,cy,cz,da,db), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Mystique %s | Nesterin  %s | Noi %s | Onas  %s | Pearl Moon %s | ',dc,dd,de,df,dg), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Pondral %s | Ragriel %s | Reyda %s | Saeya %s | Sarielle %s | ',dh,di,dj,dk,dl), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Shirmyl %s | Snowflake %s | Starburst %s | Sybella %s | Tazlen %s | ',dm,dn,doo,dp,dq), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Tisthel %s | Twilight %s | Vaella %s | Virfi %s | Wiska %s | ',dr,ds,dt,du,dv), 3, xi.msg.channel.system_3)

elseif amount == 3 then 

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('NM Hunt Kill Count Tier 3--Current Kills are %s of 50--------------------------------------',player:getCharVar('[NMHunt]TThreeKills')), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'),  xi.msg.channel.SYSTEM_3)
player:printToPlayer(string.format('Akkar %s | Angor %s | Astra %s | Azariah %s | Belstram %s | ',dw,dx,dy,dz,ea), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Bragi %s | Brulin %s | Chandrelle %s | Corym %s | Dagen %s | ',eb,ec,ed,ee,ef), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Delvin %s | Dimlinn %s | Drusila %s | Eilivur %s | Engar %s | ',eg,eh,ei,ej,ek), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Fada %s | Floki %s | Galdor %s | Glacitus %s | Gusak %s | ',el,em,en,eo,ep), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Heptin %s | Ilyrana %s | Jai-Blynn %s | Jodis %s | Killin %s | ',eq,er,es,et,eu), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Kyra %s | Lija %s | Lyra %s | Midnight %s | Mistmael %s | ',ev,ew,ex,ey,ez), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Nalra %s | Night Moon %s | Norok %s | Onnyx %s | Peregrine %s | ',fa,fb,fc,fd,fe), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Prodos %s | Rainbow %s | Rhenalyrr %s | Sakakara %s | Serpretus %s | ',ff,fg,fh,fi,fj), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Silver Star %s | Sola %s | Stardust %s | Syfas %s | Tendris %s | ',fk,fl,fm,fn,fo), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Tiznys %s | Twinkle %s | Vasha %s | Vixen %s | Wispmaral %s | ',fp,fq,fr,fs,ft), 3, xi.msg.channel.system_3)

end
end

return commandObj
