-----------------------------------
-- func: nmhuntone list 150 tier 4-6
-- desc: prints out list of kill counts
-----------------------------------
local commandObj = {}

commandObj.cmdprops =
{
    permission = 0,
    parameters = 'is'
}

local function error(player, msg)
    player:printToPlayer(msg)
    player:printToPlayer('!nmhuntone <tier>')
end

commandObj.onTrigger = function(player, amount)

    if amount == nil or amount < 1 then
        error(player, 'Invalid tier, please enter 4 - 6.')
        return
    end

local fu = player:getCharVar('[NMHunt]DE_Alea')
local fv = player:getCharVar('[NMHunt]DE_Angun')
local fw = player:getCharVar('[NMHunt]DE_Aura')
local fx = player:getCharVar('[NMHunt]DE_Azryat')
local fy = player:getCharVar('[NMHunt]DE_Blissia')
local fz = player:getCharVar('[NMHunt]DE_Braka')
local ga = player:getCharVar('[NMHunt]DE_Bulruk')
local gb = player:getCharVar('[NMHunt]DE_Chemraul')
local gc = player:getCharVar('[NMHunt]DE_Cosmic')
local gd = player:getCharVar('[NMHunt]DE_Dagurt')
local ge = player:getCharVar('[NMHunt]DE_Dermetris')
local gf = player:getCharVar('[NMHunt]DE_Dorath')
local gg = player:getCharVar('[NMHunt]DE_Duvrion')
local gh = player:getCharVar('[NMHunt]DE_Elda')
local gi = player:getCharVar('[NMHunt]DE_Eroan')
local gj = player:getCharVar('[NMHunt]DE_Faelar')
local gk = player:getCharVar('[NMHunt]DE_Foxfire')
local gl = player:getCharVar('[NMHunt]DE_Gallious')
local gm = player:getCharVar('[NMHunt]DE_Gogu')
local gn = player:getCharVar('[NMHunt]DE_Gylledha')
local go = player:getCharVar('[NMHunt]DE_Horar')
local gp = player:getCharVar('[NMHunt]DE_Ingivald')
local gq = player:getCharVar('[NMHunt]DE_Jassin')
local gr = player:getCharVar('[NMHunt]DE_Josidiah')
local gs = player:getCharVar('[NMHunt]DE_Klayden')
local gt = player:getCharVar('[NMHunt]DE_Kystal')
local gu = player:getCharVar('[NMHunt]DE_Lipith')
local gv = player:getCharVar('[NMHunt]DE_Majesty')
local gw = player:getCharVar('[NMHunt]DE_Milky Way')
local gx = player:getCharVar('[NMHunt]DE_Morthil')
local gy = player:getCharVar('[NMHunt]DE_Narbeth')
local gz = player:getCharVar('[NMHunt]DE_Nightshade')
local ha = player:getCharVar('[NMHunt]DE_Nym')
local hb = player:getCharVar('[NMHunt]DE_Ophelia')
local hc = player:getCharVar('[NMHunt]DE_Pharom')
local hd = player:getCharVar('[NMHunt]DE_Pyrder')
local he = player:getCharVar('[NMHunt]DE_Rammir')
local hf = player:getCharVar('[NMHunt]DE_Rijjat')
local hg = player:getCharVar('[NMHunt]DE_Salvor')
local hh = player:getCharVar('[NMHunt]DE_Severin')
local hi = player:getCharVar('[NMHunt]DE_Silvyr')
local hj = player:getCharVar('[NMHunt]DE_Soldelle')
local hk = player:getCharVar('[NMHunt]DE_Sterling')
local hl = player:getCharVar('[NMHunt]DE_Syfyn')
local hm = player:getCharVar('[NMHunt]DE_Thalia')
local hn = player:getCharVar('[NMHunt]DE_Toki')
local ho = player:getCharVar('[NMHunt]DE_Uldreiyn')
local hp = player:getCharVar('[NMHunt]DE_Vayzen')
local hq = player:getCharVar('[NMHunt]DE_Voggur')
local hr = player:getCharVar('[NMHunt]DE_Wistari')

local hs = player:getCharVar('[NMHunt]DE_Aleera')
local ht = player:getCharVar('[NMHunt]DE_Anya')
local hu = player:getCharVar('[NMHunt]DE_Auris')
local hv = player:getCharVar('[NMHunt]DE_Azura')
local hw = player:getCharVar('[NMHunt]DE_Blossom')
local hx = player:getCharVar('[NMHunt]DE_Breya')
local hy = player:getCharVar('[NMHunt]DE_Caelia')
local hz = player:getCharVar('[NMHunt]DE_Ciradyl')
local ia = player:getCharVar('[NMHunt]DE_Crystal')
local ib = player:getCharVar('[NMHunt]DE_Darcassan')
local ic = player:getCharVar('[NMHunt]DE_Devella')
local id = player:getCharVar('[NMHunt]DE_Doreah')
local ie = player:getCharVar('[NMHunt]DE_Dynastra')
local lp = player:getCharVar('[NMHunt]DE_Eldar')
local ig = player:getCharVar('[NMHunt]DE_Erthel')
local ih = player:getCharVar('[NMHunt]DE_Faelyn')
local ii = player:getCharVar('[NMHunt]DE_Freya')
local ij = player:getCharVar('[NMHunt]DE_Gandor')
local ik = player:getCharVar('[NMHunt]DE_Gold Horn')
local il = player:getCharVar('[NMHunt]DE_Hadena')
local im = player:getCharVar('[NMHunt]DE_Hungus')
local lq = player:getCharVar('[NMHunt]DE_Ioguss')
local io = player:getCharVar('[NMHunt]DE_Jayldrog')
local ip = player:getCharVar('[NMHunt]DE_Kalodor')
local iq = player:getCharVar('[NMHunt]DE_Kolzreid')
local ir = player:getCharVar('[NMHunt]DE_Lago')
local is = player:getCharVar('[NMHunt]DE_Lofar')
local it = player:getCharVar('[NMHunt]DE_Malfas')
local iu = player:getCharVar('[NMHunt]DE_Minelle')
local iv = player:getCharVar('[NMHunt]DE_Mortusra')
local iw = player:getCharVar('[NMHunt]DE_Narvari')
local ix = player:getCharVar('[NMHunt]DE_Nightwind')
local iy = player:getCharVar('[NMHunt]DE_Nyssa')
local iz = player:getCharVar('[NMHunt]DE_Oribel')
local ja = player:getCharVar('[NMHunt]DE_Phyrra')
local jb = player:getCharVar('[NMHunt]DE_Quamara')
local jc = player:getCharVar('[NMHunt]DE_Randil')
local jd = player:getCharVar('[NMHunt]DE_Rorik')
local je = player:getCharVar('[NMHunt]DE_Sanguisus')
local jf = player:getCharVar('[NMHunt]DE_Shadoras')
local jg = player:getCharVar('[NMHunt]DE_Sirius')
local jh = player:getCharVar('[NMHunt]DE_Solstice')
local ji = player:getCharVar('[NMHunt]DE_Sudryl')
local jj = player:getCharVar('[NMHunt]DE_Taena')
local jk = player:getCharVar('[NMHunt]DE_Thingol')
local jl = player:getCharVar('[NMHunt]DE_Turgon')
local jm = player:getCharVar('[NMHunt]DE_Usha')
local jn = player:getCharVar('[NMHunt]DE_Vesryn')
local jo = player:getCharVar('[NMHunt]DE_Vyn')
local jp = player:getCharVar('[NMHunt]DE_Withil')

local jq = player:getCharVar('[NMHunt]DE_Alva')
local jr = player:getCharVar('[NMHunt]DE_Aqrilla')
local js = player:getCharVar('[NMHunt]DE_Austi')
local jt = player:getCharVar('[NMHunt]DE_Balrus')
local ju = player:getCharVar('[NMHunt]DE_Bonesnapper')
local jv = player:getCharVar('[NMHunt]DE_Brilbelle')
local jw = player:getCharVar('[NMHunt]DE_Caldor')
local jx = player:getCharVar('[NMHunt]DE_Ciscra')
local jy = player:getCharVar('[NMHunt]DE_Daealla')
local jz = player:getCharVar('[NMHunt]DE_Darfin')
local ka = player:getCharVar('[NMHunt]DE_Dezaral')
local kb = player:getCharVar('[NMHunt]DE_Drachenstein')
local kc = player:getCharVar('[NMHunt]DE_Earthtaker')
local kd = player:getCharVar('[NMHunt]DE_Electra')
local ke = player:getCharVar('[NMHunt]DE_Esmeralla')
local kf = player:getCharVar('[NMHunt]DE_Farkas')
local kg = player:getCharVar('[NMHunt]DE_Frostar')
local kh = player:getCharVar('[NMHunt]DE_Gaylia')
local ki = player:getCharVar('[NMHunt]DE_Golden Moon')
local kj = player:getCharVar('[NMHunt]DE_Haela')
local kk = player:getCharVar('[NMHunt]DE_Igninitis')
local kl = player:getCharVar('[NMHunt]DE_Ismzal')
local km = player:getCharVar('[NMHunt]DE_Jewel')
local kn = player:getCharVar('[NMHunt]DE_Kalseru')
local ko = player:getCharVar('[NMHunt]DE_Kuskyn')
local kp = player:getCharVar('[NMHunt]DE_Laimus')
local kq = player:getCharVar('[NMHunt]DE_Luna')
local kr = player:getCharVar('[NMHunt]DE_Malok')
local ks = player:getCharVar('[NMHunt]DE_Mireille')
local kt = player:getCharVar('[NMHunt]DE_Myrinn')
local ku = player:getCharVar('[NMHunt]DE_Neldor')
local kv = player:getCharVar('[NMHunt]DE_Nightwing')
local kw = player:getCharVar('[NMHunt]DE_Oddfinnur')
local kx = player:getCharVar('[NMHunt]DE_Orion')
local ky = player:getCharVar('[NMHunt]DE_Pindious')
local kz = player:getCharVar('[NMHunt]DE_Quintus')
local la = player:getCharVar('[NMHunt]DE_Remus')
local lb = player:getCharVar('[NMHunt]DE_Rotnam')
local lc = player:getCharVar('[NMHunt]DE_Saphil')
local ld = player:getCharVar('[NMHunt]DE_Sheedra')
local le = player:getCharVar('[NMHunt]DE_Skeltos')
local lf = player:getCharVar('[NMHunt]DE_Soril')
local lg = player:getCharVar('[NMHunt]DE_Sulfu')
local lh = player:getCharVar('[NMHunt]DE_Talila')
local li = player:getCharVar('[NMHunt]DE_Throar')
local lj = player:getCharVar('[NMHunt]DE_Turilla')
local lk = player:getCharVar('[NMHunt]DE_Usunaar')
local ll = player:getCharVar('[NMHunt]DE_Viktas')
local lm = player:getCharVar('[NMHunt]DE_Wilda')
local ln = player:getCharVar('[NMHunt]DE_Wynstar')

if amount == 4 then 

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('NM Hunt Kill Count Tier 4--Current Kills are %s of 50--------------------------------------',player:getCharVar('[NMHunt]TFourKills')), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'),  xi.msg.channel.SYSTEM_3)
player:printToPlayer(string.format('Alea %s | Angun %s | Aura %s | Azryat %s | Blissia %s | ',fu,fv,fw,fx,fy), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Braka %s | Bulruk %s | Chemraul %s | Cosmic %s | Dagurt %s | ',fz,ga,gb,gc,gd), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Dermetris %s | Dorath %s | Duvrion %s | Elda %s | Eroan %s | ',ge,gf,gg,gh,gi), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Faelar %s | Foxfire %s | Gallious %s | Gogu %s | Gylledha %s | ',gj,gk,gl,gm,gn), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Horar %s | Ingivald %s | Jassin %s | Josidiah %s | Klayden %s | ',go,gp,gq,gr,gs), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Kystal %s | Lipith %s | Majesty %s | Milky Way %s | Morthil %s | ',gt,gu,gv,gw,gx), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Narbeth %s | Nightshade %s | Nym %s | Ophelia %s | Pharom  %s | ',gy,gz,ha,hb,hc), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Pyrder  %s | Rammir %s | Rijjat %s | Salvor %s | Severin %s | ',hd,he,hf,hg,hh), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Silvyr  %s | Soldelle %s | Sterling %s | Syfyn %s | Thalia %s | ',hi,hj,hk,hl,hm), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Toki %s | Uldreiyn %s | Vayzen %s | Voggur %s | Wistari %s | ',hn,ho,hp,hq,hr), 3, xi.msg.channel.system_3)

elseif amount == 5 then 

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('NM Hunt Kill Count Tier 5--Current Kills are %s of 50--------------------------------------',player:getCharVar('[NMHunt]TFiveKills')), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'),  xi.msg.channel.SYSTEM_3)
player:printToPlayer(string.format('Aleera %s | Anya %s | Auris %s | Azura %s | Blossom %s | ',hs,ht,hu,hv,hw), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Breya %s | Caelia %s | Ciradyl %s | Crystal %s | Darcassan %s | ',hx,hy,hz,ia,ib), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Devella %s | Doreah  %s | Dynastra %s | Eldar %s | Erthel %s | ',ic,id,ie,lp,ig), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Faelyn %s | Freya %s | Gandor %s | Gold Horn %s | Hadena %s | ',ih,ii,ij,ik,il), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Hungus %s | Ioguss %s | Jayldrog %s | Kalodor %s | Kolzreid %s | ',im,lq,io,ip,iq), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Lago %s | Lofar %s | Malfas %s | Minelle %s | Mortusra %s | ',ir,is,it,iu,iv), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Narvari %s | Nightwind %s | Nyssa %s | Oribel %s | Phyrra %s | ',iw,ix,iy,iz,ja), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Quamara %s | Randil %s | Rorik %s | Sanguisus %s | Shadoras %s | ',jb,jc,jd,je,jf), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Sirius %s | Solstice %s | Sudryl  %s | Taena %s | Thingol  %s | ',jg,jh,ji,jj,jk), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Turgon  %s | Usha %s | Vesryn %s | Vyn %s | Withil %s | ',jl,jm,jn,jo,jp), 3, xi.msg.channel.system_3)

elseif amount == 6 then 

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('NM Hunt Kill Count Tier 6--Current Kills are %s of 50--------------------------------------',player:getCharVar('[NMHunt]TSixKills')), xi.msg.channel.SYSTEM_3)

player:printToPlayer(string.format('-------------------------------------------------------------------------------------------'),  xi.msg.channel.SYSTEM_3)
player:printToPlayer(string.format('Alva %s | Aqrilla %s | Austi %s | Balrus %s | Bonesnapper %s | ',jq,jr,js,jt,ju), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Brilbelle %s | Caldor %s | Ciscra %s | Daealla %s | Darfin %s | ',jv,jw,jx,jy,jz), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Dezaral %s | Drachenstein %s | Earthtaker %s | Electra %s | Esmeralla %s | ',ka,kb,kc,kd,ke), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Farkas %s | Frostar %s | Gaylia %s | Golden Moon %s | Haela %s | ',kf,kg,kh,ki,kj), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Igninitis %s | Ismzal %s | Jewel %s | Kalseru %s | Kuskyn %s | ',kk,kl,km,kn,ko), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Laimus %s | Luna %s | Malok %s | Mireille %s | Myrinn %s | ',kp,kq,kr,ks,kt), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Neldor  %s | Nightwing %s | Oddfinnur %s | Orion %s | Pindious %s | ',ku,kv,kw,kx,ky), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Quintus %s | Remus %s | Rotnam %s | Saphil %s | Sheedra %s | ',kz,la,lb,lc,ld), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Skeltos %s | Soril %s | Sulfu %s | Talila %s | Throar %s | ',le,lf,lg,lh,li), 3, xi.msg.channel.system_3)
player:printToPlayer(string.format('Turilla %s | Usunaar  %s | Viktas %s | Wilda %s | Wynstar %s | ',lj,lk,ll,lm,ln), 3, xi.msg.channel.system_3)
end

end

return commandObj
